# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - master
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "xuedongwang"
- git config --global user.email "npm@wangxuedong.com"

install:
- npm i
script:
- npm run test:all